name: Realestate Turkey
favicon: null
layout_spectrum: 0.9005832942202687
typography_spectrum: 0.3591363946907222
title: Your Professional Realestate Broker in Turkey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6492968539241701
  lightness: 0.612704805098474
  saturation: 0.07400895631872118
  rhythmicContrast: 0.4665361591614783
purpose: []
